[project]
name = "ai-chat-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "av>=17.0.1",
    "discord-py[voice]>=2.7.1",
    "flask>=3.1.3",
    "flask-sock>=0.7.0",
    "gradio-client>=2.5.0",
    "gtts>=2.5.4",
    "numpy>=2.4.6",
    "openai>=2.30.0",
    "pillow>=12.2.0",
    "pynacl==1.5.0",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "spotdl>=4.4.4",
    "syncedlyrics>=1.0.1",
    "twitchio==2.10.0",
    "yt-dlp>=2026.3.17",
]
